/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cell: typeof import('./src/components/Cell/index.vue')['default']
    Engine: typeof import('./src/components/Engine/index.vue')['default']
    Page: typeof import('./src/components/Page/index.vue')['default']
    Render: typeof import('./src/components/Render/index.vue')['default']
    Row: typeof import('./src/components/Row/index.vue')['default']
  }
}
