/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./components/Action/index.vue')['default']
    Calendar: typeof import('./components/ProFormField/Calendar.vue')['default']
    Cascader: typeof import('./components/ProFormField/Cascader.vue')['default']
    Cell: typeof import('./components/Cell/index.vue')['default']
    CellGroup: typeof import('./components/CellGroup/index.vue')['default']
    DatePicker: typeof import('./components/ProFormField/DatePicker.vue')['default']
    Divider: typeof import('./components/Divider/index.vue')['default']
    Elevator: typeof import('./components/Elevator/index.vue')['default']
    Engine: typeof import('./components/Engine/index.vue')['default']
    FixedNav: typeof import('./components/FixedNav/index.vue')['default']
    Grid: typeof import('./components/Grid/index.vue')['default']
    Icon: typeof import('./components/Icon/index.vue')['default']
    Indicator: typeof import('./components/Indicator/index.vue')['default']
    Navbar: typeof import('./components/Navbar/index.vue')['default']
    Page: typeof import('./components/Page/index.vue')['default']
    Picker: typeof import('./components/ProFormField/Picker.vue')['default']
    ProForm: typeof import('./components/ProForm/index.vue')['default']
    Render: typeof import('./components/Render/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./components/Row/index.vue')['default']
    Searchbar: typeof import('./components/ProFormField/Searchbar.vue')['default']
    ShortPassword: typeof import('./components/ProFormField/ShortPassword.vue')['default']
    Sticky: typeof import('./components/Sticky/index.vue')['default']
    Tabs: typeof import('./components/Tabs/index.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheLogo: typeof import('./components/TheLogo.vue')['default']
    Uploader: typeof import('./components/ProFormField/Uploader.vue')['default']
    UserCenter: typeof import('./components/UserCenter/index.vue')['default']
  }
}
